name: Build Docker Image

on:
  push:
    branches:
      - "master"
      - 'v*.*.*'
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  build_postgres16_1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags: ['16.1', 'latest']
        platform: ['linux/amd64', 'linux/arm64']
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      - name: 'Login to Github Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_TOKEN }}
      - name: 'Build & Push PHP Image'
        run: make release POSTGRES_VERSION=16.1 TAG=${{ matrix.tags }} PLATFORM=${{ matrix.platform }}